web_controllers:
    resource: '../src/UI/Http/Web/Controllers/'
    type: attribute

api_controllers:
    resource: '../src/UI/Http/Rest/Controllers/'
    type: attribute
    prefix: /api

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }